server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdojo?createDatabaseIfNotExist=true
    username: root
    password: devdojo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#spring:
#  application:
#    name: course
#  jpa:
#    show-sql: false
#      hibernate:
#        ddl-auto: update
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#  jmx:
#    enabled: false
#    datasource:
#      url: jdbc:mysql://localhost:3306/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
#      username: root
#      password: devdojo

